name: Elasticsearch Connectable
abbreviation: redisconn
checker: codicastudio\Health\Checkers\PortCheck
notify: true
column_size: 3
error_message: "Could not connect to %s on port %s"
targets:
  - localhost:
      hostname: localhost
      port: 9200
      timeout: 2
