name: LocalStorage
abbreviation: lclstrg
checker: codicastudio\Health\Checkers\CloudStorage
notify: true
error_message: "Cloud storage is not retrieving files correctly."
column_size: 3
targets:
  - default:
      driver: local
      file: codicastudio-health-storage-testfile.txt
      contents: "{{ \\Illuminate\\Support\\Str::random(32) }}"
