name: Queue
abbreviation: queue
checker: codicastudio\Health\Checkers\Queue
error_message: "Queue system is not working properly."
column_size: 3
targets:
  - default:
      test_job: codicastudio\Health\Support\Jobs\TestJob
      cache_instance: cache
      notify: true
      connection: ""
