name: Routes Cached
abbreviation: rtcch
checker: codicastudio\Health\Checkers\Expression
notify: true
column_size: 3
error_message: "Routes are not cached"
targets:
  - default:
      expression_value: "app()->routesAreCached()"
      should_return: true
